name: flutter_app_log_desktop_app
version: 0.1.0
publish_to: none
description: App日志管理软件
environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  appwrite: ^13.1.1
  flutter_smart_dialog: ^4.9.8+5
  intl: ^0.20.1
  path_provider: ^2.1.5
  path: ^1.9.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
