name: flutter_app_log_desktop_app
version: 1.0.0+1
publish_to: none
description: App日志管理软件
environment:
  sdk: ^3.5.4
  flutter: ^3.24.5

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  realm: ^20.0.0
  appwrite: ^13.1.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
