name: Flutter macOS and Windows Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS app
        run: flutter build macos --release

      - name: Compress macOS app
        run: ditto -c -k --sequesterRsrc --keepParent build/macos/Build/Products/Release/flutter_app_log_desktop_app.app build/macos/Build/Products/Release/flutter_app_log_desktop_app-macos.zip

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: build/macos/Build/Products/Release/flutter_app_log_desktop_app-macos.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Compress Windows app
        run: Compress-Archive -Path build/windows/x64/runner/Release/flutter_app_log_desktop_app.exe -DestinationPath build/windows/x64/runner/Release/flutter_app_log_desktop_app-windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: build/windows/x64/runner/Release/flutter_app_log_desktop_app-windows.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows]
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-artifact

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact

      - name: Upload macOS release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: flutter_app_log_desktop_app-macos.zip
          asset_name: flutter_app_log_desktop_app-macos.zip
          asset_content_type: application/zip

      - name: Upload Windows release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: flutter_app_log_desktop_app-windows.zip
          asset_name: flutter_app_log_desktop_app-windows.zip
          asset_content_type: application/zip
    